routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth routes
Auth::routes(['verify' => true]);
Route::get('/banned', 'Auth\UserController@banned')->name('banned');

// Public Pages
Route::get('/', 'HomeController@index')->name('home');
Route::get('/contact', 'HomeController@contact')->name('contact');

// Profile
Route::get('/profile', 'Auth\UserController@profile')->name('profile');
Route::post('/profile', 'Auth\UserController@update');

// Issues
Route::get('/issues', 'IssueController@index')->name('issues.index');
Route::get('/issues/{issue}', 'IssueController@show')->name('issues.show');
Route::get('/issues/{issue}/buy', 'Auth\IssueController@buyForm')->name('issues.buy');
Route::get('/issues/{issue}/read', 'Auth\IssueController@read')->name('issues.read');
Route::get('/issues/{issue}/pdf', 'Auth\IssueController@pdf')->name('issues.pdf');

// Packages
Route::get('/packages', 'PackageController@index')->name('packages.index');
Route::get('/packages/{package}/buy', 'Auth\PackageController@buyForm')->name('packages.buy');

// #StayHome for Corona Virus
Route::get('/stay-home', 'PackageController@stayHome')->name('packages.stayHome');

// My Purchases
Route::get('/my-purchases', 'Auth\UserController@myPurchases')->name('my-purchases');

// Order History
Route::get('/order-history', 'Auth\UserController@orderHistory')->name('order-history');

// Payment pages
Route::post('/paytr/callback', 'OrderController@paytrCallback')->name('paytr.callback');
Route::get('/paytr/error', 'OrderController@paytrErrorPage')->name('paytr.error_page');

// Admin Routes
Route::prefix('admin')->name('admin.')->group(function () {

    // Dashboard
    Route::get('/', 'Admin\HomeController@index')->name('dashboard');

    // Users
    Route::resource('/users', 'Admin\UserController')->except([
        'show', 'destroy'
    ]);

    // Issues
    Route::resource('/issues', 'Admin\IssueController')->except([
        'show', 'destroy'
    ]);

    // Packages
    Route::resource('/packages', 'Admin\PackageController')->except([
        'show', 'destroy'
    ]);

    // Order History
    Route::get('/orders', 'Admin\OrderController@index')->name('orders.index');

    // User Logs
    Route::get('/logs', 'Admin\LogController@index')->name('logs.index');

    // Send email
    Route::get('/email', 'Admin\EmailController@form')->name('email.form');
    Route::get('/email/send/{user_id}/{issue_id}', 'Admin\EmailController@send')->name('email.send');
});

app/Issue.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Issue extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'slug', 'title', 'issue', 'price', 'month', 'language', 'preamble', 'content'
    ];

    /**
     * The attributes that are custom model variables.
     *
     * @var array
     */
    protected $appends = [
        'is_purchased'
    ];

    public function getIsPurchasedAttribute()
    {
        if (!Auth::check())
            return false;

        $purchases = Auth::user()->{'purchases_' . $this->language};

        return in_array($this->issue, $purchases);
    }
}

app/Http/Controllers/Admin/IssueController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helper\Datatables;
use App\Issue;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\AdminController;
use Illuminate\Support\Facades\Session;
use League\Flysystem\FileExistsException;

class IssueController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->get('json'))
            return response()->json(
                Datatables::simple($request->all(), 'issues', 'id', $this->issueService->getDatatableColumns())
            );

        return view('admin.datatables', [
            'title' => 'Sayılar',
            'thead' => ['id', 'Başlık', 'Sayı', 'Fiyat', 'Ay/Yıl', 'Dil', 'Kapak', 'Düzenle'],
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.issues.create', [
            'issues_all_count' => Issue::all('id')->count()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validation
        $request->validate([
            'price' => ['required', 'between:0,99.99'],
            'issue' => ['required', 'integer'],
            'month' => ['required', 'string'],
            'language' => ['required', 'string', 'regex:(tr|en)'],
            'cover' => ['required', 'image', 'mimes:jpeg'],
            'pdf' => ['required', 'mimes:pdf'],
            'content' => ['required', 'string'],
            'preamble' => ['required', 'string'],
        ]);

        $data = $this->issueService->store($request);
        Issue::create($data);

        // Redirect Issues page
        Session::flash('class', 'success');
        Session::flash('message', 'Yeni sayi başarıyla yüklendi! Üyelere hatırlatma epostası göndermeyi unutmayın!');
        return redirect()->route('admin.issues.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $issues = Issue::all();
        $issue = $issues->find($id);

        return view('admin.issues.edit', [
            'issue' => $issue,
            'issues_all_count' => $issues->count()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Validation
        $request->validate([
            'price' => ['required', 'between:0,99.99'],
            'issue' => ['required', 'integer'],
            'month' => ['required', 'string'],
            'language' => ['required', 'string', 'regex:(tr|en)'],
            'cover' => ['image', 'mimes:jpeg'],
            'pdf' => ['mimes:pdf'],
            'content' => ['required', 'string'],
            'preamble' => ['required', 'string'],
        ]);

        $issue = Issue::findOrFail($id);

        // Create title
        $title = 'Arka Kapı Dergi Sayı ' . $request->input('issue');
        if ($request->input('language') == 'en')
            $title = 'Arka Kapı Magazine Issue ' . $request->input('issue');

        // Create slug
        $slug = str_slug($title, '-', 'tr');

        try {
            $this->issueService->updateCover($request, $issue, $slug);
            $this->issueService->updatePdf($request, $issue, $slug);
        } catch (FileExistsException $e) {
            Session::flash('class', 'danger');
            Session::flash('message', 'Seçtiğiniz Sayı ve Dile ait bir sayı zaten var! Üzerine yazamazsınız!');
            return $this->edit($id);
        }

        // Edit issue
        $data = $request->all();
        $data['slug'] = $slug;
        $data['title'] = $title;
        $issue->update($data);

        // Redirect Issues page
        Session::flash('class', 'success');
        Session::flash('message', 'Sayı başarıyla güncellendi!');

        return redirect()->route('admin.issues.edit', $id);
    }

}

app/Http/Controllers/IssueController.php
<?php

namespace App\Http\Controllers;

use App\Issue;

class IssueController extends Controller
{
    /**
     * Show the all issues page.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('issue.index', [
            'title' => __('All Issues'),
            'issues' => Issue::orderBy('language', app()->getLocale() == 'tr' ? 'desc' : 'asc')
                ->orderBy('issue', 'desc')
                ->get()
        ]);
    }

    /**
     * Issue detail page.
     *
     * @param  string $slug
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function show($slug)
    {
        $issue = Issue::where('slug', $slug)->firstOrFail();

        return view('issue.show', [
            'title' => $issue->title,
            'issue' => $issue
        ]);
    }

}

resources/views/admin/issues/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-fluid">
        <div class="card mb-3">
            <div class="card-header">
                Yeni Sayı Ekle
            </div>
            <div class="card-body">
                <form action="{{ route('admin.issues.store') }}" method="post" enctype="multipart/form-data">

                    @csrf

                    <div class="form-row">
                        <div class="col-md-4 mb-3">
                            <label for="price"><b>Ücret</b> <i>Dil Türkçe seçilir ise birim TL, İngilizce seçilir ise birim USD olur.</i></label>
                            <input id="price" name="price" type="number" class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}" placeholder="XX.YY" step="0.01" value="{{ old('price') }}" required>
                            @if ($errors->has('price'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('price') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="issue"><b>Sayı</b></label>
                            <select id="issue" name="issue" class="form-control{{ $errors->has('issue') ? ' is-invalid' : '' }}" required>
                                <option value="">-- Seçiniz --</option>
                                @for($i = 1; $i <= $issues_all_count + 3; $i++)
                                    <option value="{{ $i }}">Sayı {{ $i }}</option>
                                @endfor
                            </select>
                            @if ($errors->has('issue'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('issue') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="pdf"><b>Dijital Dergi</b> <i>PDF olmalı.</i></label>
                            <input id="pdf" name="pdf" type="file" class="form-control-file{{ $errors->has('pdf') ? ' is-invalid' : '' }}" required>
                            @if ($errors->has('pdf'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('pdf') }}
                                </div>
                            @endif
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-md-4 mb-3">
                            <label for="month"><b>Aylar ve Yıl</b> <i>Örneğin; 02-03 2019</i></label>
                            <input id="month" name="month" type="text" class="form-control{{ $errors->has('month') ? ' is-invalid' : '' }}" placeholder="02-03 2019" value="{{ old('month') }}" required>
                            @if ($errors->has('month'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('month') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="language"><b>Dil</b></label>
                            <select id="language" name="language" class="form-control{{ $errors->has('language') ? ' is-invalid' : '' }}" required>
                                <option value="">-- Seçiniz --</option>
                                <option value="tr">Türkçe (Arka Kapı Dergi)</option>
                                <option value="en">İngilizce (Arka Kapı Magazine)</option>
                            </select>
                            @if ($errors->has('language'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('language') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="cover"><b>Kapak</b> <i>JPG olmalı.</i></label>
                            <input id="cover" name="cover" type="file" class="form-control-file{{ $errors->has('cover') ? ' is-invalid' : '' }}" required>
                            @if ($errors->has('cover'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('cover') }}
                                </div>
                            @endif
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-md-12 mb-3">
                            <label for="content"><b>İçerik</b></label>
                            <textarea id="content" name="content" class="summernote form-control-file{{ $errors->has('content') ? ' is-invalid' : '' }}" required>
                                {{ old('content') }}
                            </textarea>
                            @if ($errors->has('content'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('content') }}
                                </div>
                            @endif
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-md-12 mb-3">
                            <label for="preamble"><b>Önsöz</b></label>
                            <textarea id="preamble" name="preamble" class="summernote form-control-file{{ $errors->has('preamble') ? ' is-invalid' : '' }}" required>
                                {{ old('preamble') }}
                            </textarea>
                            @if ($errors->has('preamble'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('preamble') }}
                                </div>
                            @endif
                        </div>
                    </div>

                    <button class="btn btn-success" type="submit">Gönder</button>

                </form>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script>
        $(document).ready(function () {
            $('.summernote').summernote({
                height: 300
            });
        });
    </script>
@stop

resources/views/admin/issues/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-fluid">

        <div class="card mb-3">
            <div class="card-header">
                Düzenle: {{ $issue->title }}
            </div>
            <div class="card-body">
                <form action="{{ route('admin.issues.update', $issue->id) }}" method="post" enctype="multipart/form-data">

                    <input name="_method" type="hidden" value="PATCH">

                    @csrf

                    <div class="form-row">
                        <div class="col-md-4 mb-3">
                            <label for="price"><b>Ücret</b> <i>Dil Türkçe seçilir ise birim TL, İngilizce seçilir ise birim USD olur.</i></label>
                            <input id="price" name="price" type="number" class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}" placeholder="XX.YY" step="0.01" value="{{ $issue->price }}" required>
                            @if ($errors->has('price'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('price') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="issue"><b>Sayı</b></label>
                            <select id="issue" name="issue" class="form-control{{ $errors->has('issue') ? ' is-invalid' : '' }}" required>
                                @for($i = 1; $i <= $issues_all_count + 6; $i++)
                                    <option value="{{ $i }}" {{ $issue->issue == $i ? 'selected' : '' }}>Sayı {{ $i }}</option>
                                @endfor
                            </select>
                            @if ($errors->has('issue'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('issue') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="pdf"><b>Dijital Dergi</b> <i>PDF olmalı.</i> <a href="{{ route('issues.pdf', $issue->slug) }}" target="_blank">{{ $issue->slug }}.pdf</a></label>
                            <input id="pdf" name="pdf" type="file" class="form-control-file{{ $errors->has('pdf') ? ' is-invalid' : '' }}">
                            @if ($errors->has('pdf'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('pdf') }}
                                </div>
                            @endif
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-md-4 mb-3">
                            <label for="month"><b>Aylar ve Yıl</b> <i>Örneğin; 02-03 2019</i></label>
                            <input id="month" name="month" type="text" class="form-control{{ $errors->has('month') ? ' is-invalid' : '' }}" placeholder="02-03 2019" value="{{ $issue->month }}" required>
                            @if ($errors->has('month'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('month') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="language"><b>Dil</b></label>
                            <select id="language" name="language" class="form-control{{ $errors->has('language') ? ' is-invalid' : '' }}" required>
                                <option value="tr" {{ $issue->language == 'tr' ? 'selected' : '' }}>Türkçe (Arka Kapı Dergi)</option>
                                <option value="en" {{ $issue->language == 'en' ? 'selected' : '' }}>İngilizce (Arka Kapı Magazine)</option>
                            </select>
                            @if ($errors->has('language'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('language') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="cover"><b>Kapak</b> <i>JPG olmalı.</i> <a href="{{ config('app.url') . '/storage/' . $issue->slug }}.jpg" target="_blank">{{ $issue->slug }}.jpg</a></label>
                            <input id="cover" name="cover" type="file" class="form-control-file{{ $errors->has('cover') ? ' is-invalid' : '' }}">
                            @if ($errors->has('cover'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('cover') }}
                                </div>
                            @endif
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-md-12 mb-3">
                            <label for="content"><b>İçerik</b></label>
                            <textarea id="content" name="content" class="summernote form-control-file{{ $errors->has('content') ? ' is-invalid' : '' }}" required>
                                {{ $issue->content }}
                            </textarea>
                            @if ($errors->has('content'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('content') }}
                                </div>
                            @endif
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-md-12 mb-3">
                            <label for="preamble"><b>Önsöz</b></label>
                            <textarea id="preamble" name="preamble" class="summernote form-control-file{{ $errors->has('preamble') ? ' is-invalid' : '' }}" required>
                                {{ $issue->preamble }}
                            </textarea>
                            @if ($errors->has('preamble'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('preamble') }}
                                </div>
                            @endif
                        </div>
                    </div>

                    <button class="btn btn-success" type="submit">Gönder</button>

                </form>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script>
        $(document).ready(function () {
            $('.summernote').summernote({
                height: 300
            });
        });
    </script>
@stop