routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth routes
Auth::routes(['verify' => true]);
Route::get('/banned', 'Auth\UserController@banned')->name('banned');

// Public Pages
Route::get('/', 'HomeController@index')->name('home');
Route::get('/contact', 'HomeController@contact')->name('contact');

// Profile
Route::get('/profile', 'Auth\UserController@profile')->name('profile');
Route::post('/profile', 'Auth\UserController@update');

// Issues
Route::get('/issues', 'IssueController@index')->name('issues.index');
Route::get('/issues/{issue}', 'IssueController@show')->name('issues.show');
Route::get('/issues/{issue}/buy', 'Auth\IssueController@buyForm')->name('issues.buy');
Route::get('/issues/{issue}/read', 'Auth\IssueController@read')->name('issues.read');
Route::get('/issues/{issue}/pdf', 'Auth\IssueController@pdf')->name('issues.pdf');

// Packages
Route::get('/packages', 'PackageController@index')->name('packages.index');
Route::get('/packages/{package}/buy', 'Auth\PackageController@buyForm')->name('packages.buy');

// #StayHome for Corona Virus
Route::get('/stay-home', 'PackageController@stayHome')->name('packages.stayHome');

// My Purchases
Route::get('/my-purchases', 'Auth\UserController@myPurchases')->name('my-purchases');

// Order History
Route::get('/order-history', 'Auth\UserController@orderHistory')->name('order-history');

// Payment pages
Route::post('/paytr/callback', 'OrderController@paytrCallback')->name('paytr.callback');
Route::get('/paytr/error', 'OrderController@paytrErrorPage')->name('paytr.error_page');

// Admin Routes
Route::prefix('admin')->name('admin.')->group(function () {

    // Dashboard
    Route::get('/', 'Admin\HomeController@index')->name('dashboard');

    // Users
    Route::resource('/users', 'Admin\UserController')->except([
        'show', 'destroy'
    ]);

    // Issues
    Route::resource('/issues', 'Admin\IssueController')->except([
        'show', 'destroy'
    ]);

    // Packages
    Route::resource('/packages', 'Admin\PackageController')->except([
        'show', 'destroy'
    ]);

    // Order History
    Route::get('/orders', 'Admin\OrderController@index')->name('orders.index');

    // User Logs
    Route::get('/logs', 'Admin\LogController@index')->name('logs.index');

    // Send email
    Route::get('/email', 'Admin\EmailController@form')->name('email.form');
    Route::get('/email/send/{user_id}/{issue_id}', 'Admin\EmailController@send')->name('email.send');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'country_id', 'job', 'is_banned', 'is_admin', 'language', 'purchases_tr', 'purchases_en'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Attributes.
     *
     * @var array
     */
    protected $appends = [
        'total_tl', 'total_usd'
    ];

    public function country()
    {
        return $this->belongsTo('App\Country', 'country_id');
    }

    public function orders()
    {
        return $this->hasMany('App\Order');
    }

    public function logs()
    {
        return $this->hasMany('App\Log');
    }

    /**
     * Accessor for purchases_tr.
     *
     * @param string $value
     * @return array
     */
    public function getPurchasesTrAttribute($value)
    {
        return json_decode($value, true);
    }

    /**
     * Mutator for purchases_tr.
     *
     * @param array $value
     */
    public function setPurchasesTrAttribute($value)
    {
        $value = array_map(function ($val) {
            return (int)$val;
        }, $value);

        $this->attributes['purchases_tr'] = json_encode($value);
    }

    /**
     * Accessor for purchases_en.
     *
     * @param string $value
     * @return array
     */
    public function getPurchasesEnAttribute($value)
    {
        return json_decode($value, true);
    }

    /**
     * Mutator for purchases_en.
     *
     * @param array $value
     */
    public function setPurchasesEnAttribute($value)
    {
        $value = array_map(function ($val) {
            return (int)$val;
        }, $value);

        $this->attributes['purchases_en'] = json_encode($value);
    }

    public function getTotalTlAttribute()
    {
        return $this->orders()->where('status', 'successful')->where('language', 'tr')->sum('total');
    }

    public function getTotalUsdAttribute()
    {
        return $this->orders()->where('status', 'successful')->where('language', 'en')->sum('total');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Country;
use App\Events\UserAdded;
use App\Helper\Datatables;
use App\Issue;
use App\Order;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\AdminController;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;

class UserController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->get('json'))
            return response()->json(
                Datatables::simple($request->all(), 'users', 'id', $this->userService->getDatatableColumns())
            );

        return view('admin.datatables', [
            'title' => 'Kullanıcılar',
            'thead' => ['id', 'Admin?', 'Ban Durumu', 'Adı - Soyadı', 'Eposta', 'Ülke', 'Dil', 'Meslek', 'Düzenle'],
            'columnDefs' => [3,4,7]
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create', [
            'countries' => Country::all(),
            'issues_all_count' => Issue::all('id')->count()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'email' => ['required', 'email', 'unique:users'],
            'is_admin' => ['required', 'boolean'],
            'language' => ['required', 'string', 'regex:(tr|en)'],
            'country_id' => ['required', 'exists:countries,id'],
        ]);

        $data = $request->all();

        if (!$request->input('purchases_tr'))
            $data['purchases_tr'] = [];

        if (!$request->input('purchases_en'))
            $data['purchases_en'] = [];

        // Create user
        $user = User::create($data);

        // Trigger events
        event(new UserAdded($user));

        // Return
        Session::flash('class', 'success');
        Session::flash('message', 'Kullanıcı başarıyla eklendi!');

        return redirect()->route('admin.users.edit', $user->id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('admin.users.edit', [
            'user' => $user,
            'countries' => Country::all(),
            'issues_all_count' => Issue::all('id')->count(),
            'purchases_tr' => $user->purchases_tr,
            'purchases_en' => $user->purchases_en
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'is_admin' => ['required', 'boolean'],
            'is_banned' => ['required', 'boolean'],
            'language' => ['required', 'string', 'regex:(tr|en)'],
            'country_id' => ['required', 'exists:countries,id'],
        ]);

        $data = $request->except('email');

        // Set password (if sent)
        $data['password'] = Hash::make($request->input('password'));

        if (!$request->input('purchases_tr'))
            $data['purchases_tr'] = [];

        if (!$request->input('purchases_en'))
            $data['purchases_en'] = [];

        if (!$request->input('password'))
            unset($data['password']);

        // Update user
        User::findOrFail($id)->update($data);

        // Return
        Session::flash('class', 'success');
        Session::flash('message', 'Kullanıcı başarıyla güncellendi!');

        return redirect()->route('admin.users.edit', $id);
    }

}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-fluid">

        <form action="{{ route('admin.users.store') }}" method="post" enctype="multipart/form-data">

            @csrf

            <!-- for chrome hack -->
            <input type="email" name="email" style="opacity: 0;position: absolute;">
            <input type="password" name="password" autocomplete="new-password" style="opacity: 0;position: absolute;">

            <div class="card mb-3">
                <div class="card-header">
                    Yeni Kullanıcı Ekle
                </div>
                <div class="card-body">

                    <div class="form-row">
                        <div class="col-md-4 mb-3">
                            <label for="name"><b>Adı-Soyadı</b></label>
                            <input id="name" name="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ old('name') }}" autocomplete="off">
                            @if ($errors->has('name'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('name') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="email"><b>Eposta</b></label>
                            <input id="email" name="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" value="{{ old('email') }}" autocomplete="off" required>
                            @if ($errors->has('email'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('email') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="is_admin"><b>Admin?</b></label>
                            <select id="is_admin" name="is_admin" class="form-control{{ $errors->has('is_admin') ? ' is-invalid' : '' }}" required>
                                <option value="0">hayır</option>
                                <option value="1">evet</option>
                            </select>
                            @if ($errors->has('is_admin'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('is_admin') }}
                                </div>
                            @endif
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-md-4 mb-3">
                            <label for="job"><b>Meslek</b></label>
                            <input id="job" name="job" type="text" class="form-control{{ $errors->has('job') ? ' is-invalid' : '' }}" value="{{ old('job') }}" autocomplete="off">
                            @if ($errors->has('job'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('job') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="language"><b>Dil</b></label>
                            <select id="language" name="language" class="form-control{{ $errors->has('language') ? ' is-invalid' : '' }}" required>
                                <option value="">-- Seçiniz --</option>
                                <option value="tr">Türkçe</option>
                                <option value="en">İngilizce</option>
                            </select>
                            @if ($errors->has('language'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('language') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="country_id"><b>Ülke</b></label>
                            <select id="country_id" name="country_id" class="form-control{{ $errors->has('country_id') ? ' is-invalid' : '' }}">
                                @foreach($countries as $country)
                                    <option value="{{ $country->id }}">{{ $country->name }}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('country_id'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('country_id') }}
                                </div>
                            @endif
                        </div>
                    </div>

                    <button class="btn btn-success" type="submit">Gönder</button>

                </div>
            </div>

            <div class="card mb-3">
                <div class="card-header">
                    Satın Almalar
                </div>
                <div class="card-body">

                    <div class="form-row">
                        <div class="col-md-6 mb-3">
                            <label for="purchases_tr"><b>Arka Kapı Dergi (Türkçe)</b></label>
                            <select id="purchases_tr" name="purchases_tr[]" multiple size="10" class="form-control{{ $errors->has('purchases_tr') ? ' is-invalid' : '' }}">
                                @for($i = 1; $i <= $issues_all_count + 6; $i++)
                                    <option value="{{ $i }}">Sayı {{ $i }}</option>
                                @endfor
                            </select>
                            @if ($errors->has('purchases_tr'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('purchases_tr') }}
                                </div>
                            @endif
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="purchases_en"><b>Arka Kapı Magazine (İngilizce)</b></label>
                            <select id="purchases_en" name="purchases_en[]" multiple size="10" class="form-control{{ $errors->has('purchases_en') ? ' is-invalid' : '' }}">
                                @for($i = 1; $i <= $issues_all_count + 6; $i++)
                                    <option value="{{ $i }}">Sayı {{ $i }}</option>
                                @endfor
                            </select>
                            @if ($errors->has('purchases_en'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('purchases_en') }}
                                </div>
                            @endif
                        </div>
                    </div>

                    <button class="btn btn-success" type="submit">Gönder</button>

                </div>
            </div>

        </form>

    </div>
@stop

@section('js')
    <script>
        $('#purchases_tr').multiSelect();
        $('#purchases_en').multiSelect();
    </script>
@stop