routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth routes
Auth::routes(['verify' => true]);
Route::get('/banned', 'Auth\UserController@banned')->name('banned');

// Public Pages
Route::get('/', 'HomeController@index')->name('home');
Route::get('/contact', 'HomeController@contact')->name('contact');

// Profile
Route::get('/profile', 'Auth\UserController@profile')->name('profile');
Route::post('/profile', 'Auth\UserController@update');

// Issues
Route::get('/issues', 'IssueController@index')->name('issues.index');
Route::get('/issues/{issue}', 'IssueController@show')->name('issues.show');
Route::get('/issues/{issue}/buy', 'Auth\IssueController@buyForm')->name('issues.buy');
Route::get('/issues/{issue}/read', 'Auth\IssueController@read')->name('issues.read');
Route::get('/issues/{issue}/pdf', 'Auth\IssueController@pdf')->name('issues.pdf');

// Packages
Route::get('/packages', 'PackageController@index')->name('packages.index');
Route::get('/packages/{package}/buy', 'Auth\PackageController@buyForm')->name('packages.buy');

// #StayHome for Corona Virus
Route::get('/stay-home', 'PackageController@stayHome')->name('packages.stayHome');

// My Purchases
Route::get('/my-purchases', 'Auth\UserController@myPurchases')->name('my-purchases');

// Order History
Route::get('/order-history', 'Auth\UserController@orderHistory')->name('order-history');

// Payment pages
Route::post('/paytr/callback', 'OrderController@paytrCallback')->name('paytr.callback');
Route::get('/paytr/error', 'OrderController@paytrErrorPage')->name('paytr.error_page');

// Admin Routes
Route::prefix('admin')->name('admin.')->group(function () {

    // Dashboard
    Route::get('/', 'Admin\HomeController@index')->name('dashboard');

    // Users
    Route::resource('/users', 'Admin\UserController')->except([
        'show', 'destroy'
    ]);

    // Issues
    Route::resource('/issues', 'Admin\IssueController')->except([
        'show', 'destroy'
    ]);

    // Packages
    Route::resource('/packages', 'Admin\PackageController')->except([
        'show', 'destroy'
    ]);

    // Order History
    Route::get('/orders', 'Admin\OrderController@index')->name('orders.index');

    // User Logs
    Route::get('/logs', 'Admin\LogController@index')->name('logs.index');

    // Send email
    Route::get('/email', 'Admin\EmailController@form')->name('email.form');
    Route::get('/email/send/{user_id}/{issue_id}', 'Admin\EmailController@send')->name('email.send');
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Admin Panel | {{ config('app.name') }}</title>

    <!-- Styles -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.min.css" rel="stylesheet">
    <link href="{{ secure_asset('css/admin.css') }}" rel="stylesheet">

    @yield('css')

</head>

<body id="page-top">

<nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
    </button>
    <a class="navbar-brand mr-1" href="{{ route('admin.dashboard') }}">{{ trans('app.name') }}</a>
</nav>

<div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
        <li class="nav-item{{ Route::currentRouteName() == 'admin.dashboard' ? ' active' : '' }}">
            <a class="nav-link" href="{{ route('admin.dashboard') }}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span>
            </a>
        </li>
        <li class="nav-item{{ getParentRouteName() == 'admin.users' ? ' active' : '' }}">
            <a class="nav-link" href="{{ route('admin.users.index') }}">
                <i class="fas fa-fw fa-users"></i>
                <span>Kullanıcılar</span>
            </a>
        </li>
        <li class="nav-item{{ getParentRouteName() == 'admin.issues' ? ' active' : '' }}">
            <a class="nav-link" href="{{ route('admin.issues.index') }}">
                <i class="fas fa-fw fa-book-open"></i>
                <span>Sayılar</span>
            </a>
        </li>
        <li class="nav-item{{ getParentRouteName() == 'admin.packages' ? ' active' : '' }}">
            <a class="nav-link" href="{{ route('admin.packages.index') }}">
                <i class="fas fa-fw fa-archive"></i>
                <span>Paketler</span>
            </a>
        </li>
        <li class="nav-item {{ getParentRouteName() == 'admin.email' ? ' active' : '' }}">
            <a class="nav-link" href="{{ route('admin.email.form') }}">
                <i class="fas fa-fw fa-envelope"></i>
                <span>Eposta Gönderimi</span>
            </a>
        </li>
        <li class="nav-item {{ getParentRouteName() == 'admin.orders' ? ' active' : '' }}">
            <a class="nav-link" href="{{ route('admin.orders.index') }}">
                <i class="fas fa-fw fa-list"></i>
                <span>Satın Alma Logları</span>
            </a>
        </li>
        <li class="nav-item {{ getParentRouteName() == 'admin.logs' ? ' active' : '' }}">
            <a class="nav-link" href="{{ route('admin.logs.index') }}">
                <i class="fas fa-fw fa-sliders-h"></i>
                <span>Kullanıcı Logları</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('home') }}">
                <i class="fas fa-fw fa-backspace"></i>
                <span>Geri Dön</span>
            </a>
        </li>
    </ul>

    <div id="content-wrapper">

        <div class="container-fluid">
            @if(Session::has('message'))
                <div class="alert alert-{{Session::get('class')}}" role="alert">
                    {{Session::get('message')}}
                </div>
            @endif
        </div>

    @yield('content')

    <!-- Sticky Footer -->
        <footer class="sticky-footer">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>{{ trans('app.name') }}</span>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.content-wrapper -->

</div>
<!-- /#wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<script src="{{ secure_asset('js/admin.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js"></script>

@yield('js')

</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@if(isset($title)){{ $title }} | @endif{{ trans('app.name') }}</title>

    <!-- Favicons -->
    <link rel="shortcut icon" href="{{ secure_asset('images/favicon.png') }}">

    <!-- Open Graph Tags -->
    <meta property="og:locale" content="{{ app()->getLocale() }}" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="@if(isset($title)){{ $title }} |@endif {{ trans('app.name') }}" />
    <meta property="og:url" content="{{ url()->full() }}" />
    <meta property="og:site_name" content="{{ trans('app.name') }}" />
    <meta property="og:image" content="{{ secure_asset('images/open_graph.jpg') }}" />
    <meta property="og:image:secure_url" content="{{ secure_asset('images/open_graph.jpg') }}" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />

    <!-- Scripts -->
    <script src="{{ secure_asset('js/app.js') }}" defer></script>
    <script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5bc64da80c55ed0011c0228a&product=inline-share-buttons' async='async'></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ secure_asset('css/app.css') }}">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-139873462-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-139873462-1');
    </script>

</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ trans('app.name') }}
                </a>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('home') }}">{{ __('Homepage') }}</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('issues.index') }}">{{ __('Issues') }}</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('packages.index') }}">{{ __('Packages') }}</a>
                        </li>

                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @endif
                        @else
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('my-purchases') }}">{{ __('My Purchases') }}</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a href="{{ route('profile') }}" class="dropdown-item">{{ __('Profile') }}</a>
                                <a href="{{ route('order-history') }}" class="dropdown-item">{{ __('Order History') }}</a>
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>

                            @if(Auth::user()->is_admin)
                        <li class="nav-item">
                            <a class="nav-link" style="color: #f00;" href="{{ route('admin.dashboard') }}">{{ __('Admin Panel') }}</a>
                        </li>
                        @endif

                        </li>
                        @endguest

                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('packages.stayHome') }}">{{ __('#StayHome') }}</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <main role="main">

            <div class="container">
                @if(Session::has('message'))
                <div class="alert alert-{{ Session::get('class') }}" role="alert">
                    {{ __(Session::get('message')) }}
                </div>
                @endif
            </div>


            @yield('content')

        </main>

        <footer class="footer">
            <div class="container">
                <p class="text-muted">{{ trans('app.name') . ', ' . date('Y') }} - <a href="{{ route('contact') }}">{{ __('Contact') }}</a></p>
            </div>
        </footer>

    </div>

</body>

</html>